FROM python:3.9

# https://pypi.org/project/torchgeo/#installation-instructions
# git clone https://github.com/microsoft/torchgeo.git
# cd torchgeo
# pip install -r requirements.txt
RUN pip install numpy
RUN pip install torchgeo

# examples https://torchgeo.readthedocs.io/en/latest/tutorials/getting_started.html